'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InitialDLauncher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _180SX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_180SX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ADVload030_bg_05_n_D8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADVload030_bg_05_n_D8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ADVload030_bg_17_n_D8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADVload030_bg_17_n_D8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ADVload030_bg_19_n_D8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADVload030_bg_19_n_D8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AE85() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE85", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AE862D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE862D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AE86L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE86L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AE86T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AE86T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property akagi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("akagi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property akina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("akina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property akinaSnow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("akinaSnow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ALTEZZA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ALTEZZA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BNR32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BNR32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BNR34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BNR34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BRZ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BRZ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card4f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card4f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card4japf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card4japf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card4japm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card4japm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card4m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card4m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card5f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card5f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card5m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card5m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card6f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card6f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card6m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card6m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card7f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card7f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card7m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card7m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card8m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card8m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CELICA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CELICA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E0A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E0A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E0B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E0B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E0C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E0C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E0D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E0D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E0E() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E0E", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E0F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E0F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E1A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E1A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E1B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E1B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E1C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E1C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E1D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E1D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property E1E() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E1E", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EA11R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EA11R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EG6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EG6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EK9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EK9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EK9_CC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EK9_CC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ER34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ER34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EVO9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EVO9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FC3S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FC3S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FD3S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FD3S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FD3S_CC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FD3S_CC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FD3SRS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FD3SRS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FT86() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FT86", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GC8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GC8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GCBA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GCBA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GCBF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GCBF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GT86() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GT86", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hakone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hakone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property happogahara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("happogahara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ID7() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ID7", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ID8() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ID8", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property irohazaka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("irohazaka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JZA80_Kai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JZA80_Kai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lakeAkina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lakeAkina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property launcher_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("launcher_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property momijiline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("momijiline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MRS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MRS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property myogi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myogi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NA2_CC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NA2_CC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NA6CE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NA6CE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NA8C_Kai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NA8C_Kai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nagao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nagao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property namagari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("namagari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NB8C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NB8C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NSX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NSX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property play() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play12() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play13() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play14() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play16() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play17() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play18() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play19() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play20() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play21() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play23() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play24() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play25() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play26() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRIUS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRIUS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RX8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RX8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S2000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S2000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S2000_CC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S2000_CC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sadamine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sadamine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SIL80() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SIL80", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SUPRA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SUPRA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tsubakiLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsubakiLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tsuchisaka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsuchisaka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tsuchisakaSnow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsuchisakaSnow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tsukuba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsukuba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tsukubaSnow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tsukubaSnow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property usui() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usui", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
