Imports System.Drawing

Namespace InitialD6

    Namespace Male

        Public Class Accessories
            Public AC_00X1 As New Bitmap(My.Resources._00Y1)
            Public AC_01X1 As New Bitmap(My.Resources._01Y1)
            Public AC_02X1 As New Bitmap(My.Resources._02Y1)
            Public AC_03X1 As New Bitmap(My.Resources._03Y1)
            Public AC_04X1 As New Bitmap(My.Resources._04Y1)
            Public AC_05X1 As New Bitmap(My.Resources._05Y1)
            Public AC_06X1 As New Bitmap(My.Resources._06Y1)
            Public AC_07X1 As New Bitmap(My.Resources._07Y1)
            Public AC_08X1 As New Bitmap(My.Resources._08Y1)
            Public AC_E2X0 As New Bitmap(My.Resources.E2Y0)
            Public AC_E3X0 As New Bitmap(My.Resources.E3Y0)
            Public AC_E4X0 As New Bitmap(My.Resources.E4Y0)
            Public AC_E5X0 As New Bitmap(My.Resources.E5Y0)
            Public AC_E6X0 As New Bitmap(My.Resources.E6Y0)
            Public AC_E7X0 As New Bitmap(My.Resources.E7Y0)
            Public AC_E8X0 As New Bitmap(My.Resources.E8Y0)
            Public AC_E9X0 As New Bitmap(My.Resources.E9Y0)
            Public AC_EAX0 As New Bitmap(My.Resources.EAY0)
            Public AC_EBX0 As New Bitmap(My.Resources.EBY0)
            Public AC_ECX0 As New Bitmap(My.Resources.ECY0)
            Public AC_EDX0 As New Bitmap(My.Resources.EDY0)
            Public AC_EEX0 As New Bitmap(My.Resources.EEY0)
            Public AC_EFX0 As New Bitmap(My.Resources.EFY0)
            Public AC_F0X0 As New Bitmap(My.Resources.F0Y0)
            Public AC_F1X0 As New Bitmap(My.Resources.F1Y0)
            Public AC_F2X0 As New Bitmap(My.Resources.F2Y0)
            Public AC_F3X0 As New Bitmap(My.Resources.F3Y0)
            Public AC_F4X0 As New Bitmap(My.Resources.F4Y0)
            Public AC_F5X0 As New Bitmap(My.Resources.F5Y0)
            Public AC_F6X0 As New Bitmap(My.Resources.F6Y0)
            Public AC_F7X0 As New Bitmap(My.Resources.F7Y0)
            Public AC_F8X0 As New Bitmap(My.Resources.F8Y0)
            Public AC_F9X0 As New Bitmap(My.Resources.F9Y0)
            Public AC_FAX0 As New Bitmap(My.Resources.FAY0)
            Public AC_FBX0 As New Bitmap(My.Resources.FBY0)
            Public AC_FCX0 As New Bitmap(My.Resources.FCY0)
            Public AC_FDX0 As New Bitmap(My.Resources.FDY0)
            Public AC_FEX0 As New Bitmap(My.Resources.FEY0)
            Public AC_FFX0 As New Bitmap(My.Resources.FFY0)
        End Class

        Public Class Eyes
            Public EY_8EX0 As New Bitmap(My.Resources._8EY0)
            Public EY_8FX0 As New Bitmap(My.Resources._8FY0)
            Public EY_9AX0 As New Bitmap(My.Resources._9AY0)
            Public EY_9BX0 As New Bitmap(My.Resources._9BY0)
            Public EY_9CX0 As New Bitmap(My.Resources._9CY0)
            Public EY_9DX0 As New Bitmap(My.Resources._9DY0)
            Public EY_9EX0 As New Bitmap(My.Resources._9EY0)
            Public EY_9FX0 As New Bitmap(My.Resources._9FY0)
            Public EY_90X0 As New Bitmap(My.Resources._90Y0)
            Public EY_91X0 As New Bitmap(My.Resources._91Y0)
            Public EY_92X0 As New Bitmap(My.Resources._92Y0)
            Public EY_93X0 As New Bitmap(My.Resources._93Y0)
            Public EY_94X0 As New Bitmap(My.Resources._94Y0)
            Public EY_95X0 As New Bitmap(My.Resources._95Y0)
            Public EY_96X0 As New Bitmap(My.Resources._96Y0)
            Public EY_97X0 As New Bitmap(My.Resources._97Y0)
            Public EY_98X0 As New Bitmap(My.Resources._98Y0)
            Public EY_99X0 As New Bitmap(My.Resources._99Y0)
            Public EY_A0X0 As New Bitmap(My.Resources.A0Y0)
            Public EY_A1X0 As New Bitmap(My.Resources.A1Y0)
            Public EY_A2X0 As New Bitmap(My.Resources.A2Y0)
            Public EY_A3X0 As New Bitmap(My.Resources.A3Y0)
            Public EY_A4X0 As New Bitmap(My.Resources.A4Y0)
            Public EY_A5X0 As New Bitmap(My.Resources.A5Y0)
            Public EY_A6X0 As New Bitmap(My.Resources.A6Y0)
            Public EY_A7X0 As New Bitmap(My.Resources.A7Y0)
            Public EY_A8X0 As New Bitmap(My.Resources.A8Y0)
            Public EY_A9X0 As New Bitmap(My.Resources.A9Y0)
            Public EY_AAX0 As New Bitmap(My.Resources.AAY0)
            Public EY_ABX0 As New Bitmap(My.Resources.ABY0)
            Public EY_ACX0 As New Bitmap(My.Resources.ACY0)
            Public EY_ADX0 As New Bitmap(My.Resources.ADY0)
            Public EY_AEX0 As New Bitmap(My.Resources.AEY0)
            Public EY_AFX0 As New Bitmap(My.Resources.AFY0)
            Public EY_B0X0 As New Bitmap(My.Resources.B0Y0)
            Public EY_B1X0 As New Bitmap(My.Resources.B1Y0)
            Public EY_B2X0 As New Bitmap(My.Resources.B2Y0)
            Public EY_B3X0 As New Bitmap(My.Resources.B3Y0)
        End Class

    End Namespace
End Namespace
